version: '3.1'
services:
  app:
    container_name: cities
    image: cities
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
    environment:
      - POSTGRES_PASSWORD=cities
      - POSTGRES_USER=cities
      - POSTGRES_DB=cities
  dbpostgresql:
    image: postgres
    ports:
      - "5433:5433"
    command: -p 5433
