server:
  port: 8080
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cities
    username: cities
    password: cities
    platform: postgres
jwt:
  secret: infinum
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,heapdump,threaddump,configprops
